Evnts/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("events.urls")),
    path("accounts/", include("accounts.urls")),
    path("comments/", include('django_comments_xtd.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import (
    DeleteUserAccount,
    PasswordChange,
    PasswordChangeDone,
    RegisterUser,
    UserProfile,
    UserEditProfile,
)


app_name = "accounts"

urlpatterns = [
    path("register/", RegisterUser.as_view(), name="register"),
    path("<slug:username>/profile/", UserProfile.as_view(), name="user-profile"),
    path("<slug:username>/edit-profile/", UserEditProfile.as_view(), name="edit-profile"),
    path("<slug:username>/delete-account/", DeleteUserAccount.as_view(), name="delete-account"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", PasswordChange.as_view(), name="password_change"),
    path("password-change-done/", PasswordChangeDone.as_view(), name="password_change_done"),
]

events/urls.py
from django.urls import path

from .views import (
    AddEventView,
    Attendlist,
    CategoryDetailView,
    CategoryListView,
    DeleteEventView,
    EditEventView,
    EventDetailView,
    EventsListView,
    EventTagView,
    IndexView,
    ManageEventsView,
    PrivateEventDetailView,
    PrivateEventsView,
    SearchEventView,
)


app_name = "events"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("home/", EventsListView.as_view(), name="home"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("category/<slug:slug>/", CategoryDetailView.as_view(), name="category-detail"),
    path("private-events/", PrivateEventsView.as_view(), name="private-events"),
    path("my-private-events/<slug:slug>/", PrivateEventDetailView.as_view(), name="private-event-detail"),
    path("manage-events/", ManageEventsView.as_view(), name="manage-events"),
    path("events/<slug:slug>/", EventDetailView.as_view(), name="event-detail"),
    path("events/tags/<slug:slug>/", EventTagView.as_view(), name="event-tag"),
    path("add-event/", AddEventView.as_view(), name="add-event"),
    path("events/<slug:slug>/delete-event/", DeleteEventView.as_view(), name="delete-event"),
    path("events/<slug:slug>/edit-event/", EditEventView.as_view(), name="edit-event"),
    path("events/", SearchEventView.as_view(), name="search"),
    path("m/attend-list/", Attendlist.as_view(), name="attend-list"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


# Create your models here.
class CustomUser(AbstractUser):

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    image = models.ImageField(
        verbose_name="Profile picture",
        upload_to="media/profile pics",
        null=True,
    )
    date_of_birth = models.DateField(blank=True, null=True)
    GENDER_CHOICES = [
        ("Male", "Male"), 
        ("Female", "Female"), 
        ("Others", "Others")
    ]
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True)

    def __str__(self):
        return f"{self.username}"

    def get_absolute_url(self):
        return reverse("accounts:user-profile", args=[self.username])

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


# Forms
class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        min_length=3, 
        required=True, 
        widget=forms.TextInput(),
    )
   
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            "image",
            "username",
            "email",
            "first_name",
            "last_name",
            "gender",
            "date_of_birth",
        )


class CustomUserEditForm(UserChangeForm):
    
    class Meta:
        model = CustomUser
        fields = (
            "image",
            "username",
            "email",
            "first_name",
            "last_name",
            "date_of_birth",
        )

accounts/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeDoneView,  PasswordChangeView
from django.urls import reverse_lazy

from events.models import Event

from .forms import CustomUserCreationForm, CustomUserEditForm
from .models import CustomUser


# Create your views here.
def get_user(username: str) -> CustomUser:
    user = get_object_or_404(CustomUser, username=username)
    return user


class RegisterUser(View):

    form_class = CustomUserCreationForm
    template_name: str = "register.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Account creation was successful.")
            return redirect("events:home")
        else:
            messages.error(
                request, "Error creating account. Check and resubmit the form."
            )
        context = {"form": form}
        return render(request, self.template_name, context)


class UserProfile(View):

    template_name: str = "user_profile.html"

    def get(self, request: HttpRequest, username: str) -> HttpResponse:
        user = get_user(username)
        posted_events = Event.objects.filter(user=user)
        context = {"user": user, "user_events": posted_events}
        return render(request, self.template_name, context)


class UserEditProfile(LoginRequiredMixin, View):

    form_class = CustomUserEditForm
    template_name: str = "edit_profile.html"

    def get(self, request: HttpRequest, username: str) -> HttpResponse:
        user = get_user(username)
        if request.user == user:
            form = self.form_class(instance=user)
        else:
            return HttpResponseForbidden()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest, username: str) -> HttpResponse:
        user = get_user(username)
        if request.user == user:
            form = self.form_class(
                instance=user, data=request.POST, files=request.FILES
            )
            if form.is_valid():
                form.save()
                messages.success(request, "Profile was updated successfully.")
                return redirect(user.get_absolute_url())
            else:
                messages.error(request, "Error updating your profile.")
        else:
            return HttpResponseForbidden()
        context = {"form": form}
        return render(request, self.template_name, context)


class DeleteUserAccount(LoginRequiredMixin, View):

    template_name: str = "delete_account.html"

    def get(self, request: HttpRequest, username: str) -> HttpResponse:
        user = get_user(username)
        if request.user == user:
            context = {"user": user}
            return render(request, self.template_name, context)
        else:
            return HttpResponseForbidden()

    def post(self, request: HttpRequest, username: str) -> HttpResponse:
        user = get_user(username)
        if request.user.is_superuser or request.user == user:
            user.delete()
            return redirect("events:home")
        else:
            return HttpResponseForbidden()


class PasswordChange(PasswordChangeView):

    template_name: str = "password_change.html"
    success_url = reverse_lazy("accounts:password_change_done")


class PasswordChangeDone(PasswordChangeDoneView):

    template_name: str = "password_change_done.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        messages.success(request, "Your password has been changed successfully.")
        return render(request, self.template_name)

accounts/templates/403_error.html
{% block search %}

{% endblock %}

{% block content %}
<h1 class="text-danger"> ERROR 403! <br> You do not have the user rights to access this page. </h1>
{% endblock %}

{% block footer %}
{% endblock %}

accounts/templates/delete_account.html
{% extends 'base.html' %}


{% block title %}
<h2> Delete account </h2>
{% endblock %}


{% block content %}
<h3> {{ user.username|title }} </h3>
<form action="" method="post">
    {% csrf_token %}
    <p> Are you sure you want to delete your account? This action can not be undone! </p> 
    <button class="btn btn-danger py-2 px-3"> Delete </button>
    <a href="{{ user.get_absolute_url }}" class="btn btn-outline-dark mx-5 py-0">Cancel</a>
</form>
{% endblock %}


{% block footer %} {% endblock %}

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Edit your profile </h2>
{% endblock title %}


{% block content %}
{% if messages %}
    <div class="alert alert-danger w-75 m-5" role="alert">
        {% for message in messages %}
            <span> {{ message }} </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        {% endfor %}
    </div>
{% endif %}   

<form enctype="multipart/form-data" method="post" action="" class="form-control">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">Save changes</button>
</form>
{% endblock content %}


{% block footer %} {% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Log in </h2> 
{% endblock title %}


{% block search %}
{% endblock search %}


{% block content %}
<div class="form-control p-5">
    <form method="post" action="" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="submit">
            <a href="">Forgotten password? </a> <br>
            <button type="submit" class="btn btn-outline-success mt-5"> Log in  </button> <hr>
            <p class="mx-0"> Don't have an account? <a href="{% url 'accounts:register' %}"> Register </a> </p>
        </div>
    </form>
</div>
{% endblock content %} 


{% block footer %} {% endblock %}

accounts/templates/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Change Password </h2>
{% endblock title %}


{% block content %}
<div class="form-control p-5">
    <form action="" method="post" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        <hr>
        <button class="btn btn-outline-success mt-5"> Change password </button>
    </form>
</div>
{% endblock content %}


{% block footer %}{% endblock footer %}

accounts/templates/password_change_done.html
{% extends 'base.html' %}


{% block title %}
<h2> Password Change Done </h2>
{% endblock title %}


{% block content %}
{% if messages %}
    <div class="alert alert-success w-75 m-5" role="alert">
        {% for message in messages %}
            <span> {{ message }} </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        {% endfor %}
    </div>
{% endif %}

<div class="mt-5 text-center">
    <a href="{% url 'events:home' %}" class="btn btn-outline-primary p-1">Go to home page</a>
    <a href="{{ user.get_absolute_url }}" class="btn btn-outline-warning mx-5 p-1">Go to profile page</a>
</div>
{% endblock content %}


{% block footer %} {% endblock footer %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Register </h2>
{% endblock title %}


{% block search %}
{% endblock search %}


{% block content %}
{% if messages %}
    <div class="error-messages bg-danger">
        {% for messages in messages %}
            {{ messages }} <a href="" class="close">x</a>
        {% endfor %}
    </div>
{% endif %}

<div class="form-control p-5">
    <form enctype="multipart/form-data" method="post" action="" class="form-group">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="submit">
            <button type="submit" class="btn btn-outline-success mt-5"/> Create account </button> <hr>
            <p class="mx-0"> Already have an account? <a href="{% url 'accounts:login' %}">Login</a></p>
        </div>
    </form>
</div>
{% endblock content %}


{% block footer %} {% endblock %}

accounts/templates/user_profile.html
{% extends 'base.html' %}


{% block title %}
<h2> {{ user.username|title }} </h2>
{% endblock title %}    


{% block content %}
<div class="user my-5">
    {% if messages %}
        <div class="alert alert-success w-75 m-5" role="alert">
            {% for message in messages %}
                <span> {{ message }} </span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            {% endfor %}
        </div>
    {% endif %}
    
    {% if user.image %}
        <img src="{{ user.image.url }}" alt=""> <br>
    {% else %}
       <img src="/static/images/anon.png" alt=""> <br>
    {% endif %} 
    <hr class="m-3">
    Username: {{ user.username }} <br>
    Email: {{ user.email }} <br>
    First Name: {{ user.first_name }} <br>
    Last Name: {{ user.last_name }} <br>
    Gender: {{ user.gender }} <br>
    Date of Birth:
    {% if user.date_of_birth %}
        {{ user.date_of_birth }}
    {% else %}
        Not set
    {% endif %}  <br>

    <div class="m-3">
        {% if request.user == user %}
            <a href="{% url 'accounts:edit-profile' user.username %}" class="btn btn-outline-secondary py-1">Edit profile</a>
            <a href="{% url 'accounts:password_change' %}" class="btn btn-outline-warning py-1 m-4" >Change password</a>
            <a href="{% url 'accounts:delete-account' user.username  %}" class="btn btn-outline-danger py-1">Delete account</a>
        {% endif %}
    </div>

    <hr>
    <div class="mt-5">
        <h3> Evnts by {{ user }} </h3>
        <p> {{ user }} has posted {{ user_events.count }} evnts. </p>
        {% for events in user_events %}
            <a href="{{ events.get_absolute_url }}"> {{ events }} </a> <br>
        {% endfor %}
    </div>
</div>
{% endblock content %}


{% block footer %} {% endblock footer %}