Evnts/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("events.urls")),
    path("accounts/", include("accounts.urls")),
    path("comments/", include('django_comments_xtd.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from .views import (
    AddEventView,
    Attendlist,
    CategoryDetailView,
    CategoryListView,
    DeleteEventView,
    EditEventView,
    EventDetailView,
    EventsListView,
    EventTagView,
    IndexView,
    ManageEventsView,
    PrivateEventDetailView,
    PrivateEventsView,
    SearchEventView,
)


app_name = "events"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("home/", EventsListView.as_view(), name="home"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("category/<slug:slug>/", CategoryDetailView.as_view(), name="category-detail"),
    path("private-events/", PrivateEventsView.as_view(), name="private-events"),
    path("my-private-events/<slug:slug>/", PrivateEventDetailView.as_view(), name="private-event-detail"),
    path("manage-events/", ManageEventsView.as_view(), name="manage-events"),
    path("events/<slug:slug>/", EventDetailView.as_view(), name="event-detail"),
    path("events/tags/<slug:slug>/", EventTagView.as_view(), name="event-tag"),
    path("add-event/", AddEventView.as_view(), name="add-event"),
    path("events/<slug:slug>/delete-event/", DeleteEventView.as_view(), name="delete-event"),
    path("events/<slug:slug>/edit-event/", EditEventView.as_view(), name="edit-event"),
    path("events/", SearchEventView.as_view(), name="search"),
    path("m/attend-list/", Attendlist.as_view(), name="attend-list"),
]

events/models.py
from ckeditor.fields import RichTextField

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):

    class CategoryChoices(models.TextChoices):

        WEDDING = "Wedding"
        CONCERT = "Concert"
        PARTY = "Party"
        CONFERENCE =  "Conference"
        FESTIVAL = "Festival"
        EXHIBITION = "Exhibition"
        MEETING = "Meeting"
        SPORT = "Sport Event"
        OTHERS = "Others"
    
    name = models.CharField(max_length=20, choices=CategoryChoices.choices)
    description = models.TextField(null=True)
    slug = models.SlugField(max_length=20, null=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("events:category-detail", kwargs={"slug": self.slug})


class PrivateEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(make_private=True)


class PublicEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(make_private=False)


class Event(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True, null=True)
    attending = models.BooleanField(default=False, help_text="Will you attend this evnt?")
    users_attending = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_attend")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="events")
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to="media/event imgs", null=True, blank=True)
    slug = models.SlugField(null=True, unique=True)
    description = RichTextField()
    host = models.CharField(max_length=50, blank=True)
    special_guests = models.CharField(max_length=100, blank=True)
    venue = models.CharField(max_length=100)
    date_of_event = models.DateTimeField()
    make_private = models.BooleanField(
        verbose_name="Make Private?",
        help_text="Do you want to keep this evnt from others?",
        default=False
    )
    ticket_price = models.PositiveIntegerField(null=True)

    # Managers
    objects = models.Manager()
    tags = TaggableManager()
    public = PublicEventManager()
    private = PrivateEventManager()
    
    class Meta:
        ordering = ('-date_posted',)

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        if self.attending:
            self.users_attending.add(self.user)

    def get_absolute_url(self):
        if self.make_private:
            return reverse("events:private-event-detail", kwargs={"slug": self.slug})
        return reverse("events:event-detail", kwargs={"slug": self.slug})

    @property
    def past_event(self):
        date = timezone.now().date()
        if self.date_of_event.date() < date:
            return True


class Comment(models.Model):

    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="comments")
    username = models.CharField(max_length=20)
    comment = models.TextField()
    reply = models.ForeignKey("self", on_delete=models.CASCADE, related_name="replies", null=True)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.username}, {self.comment}"

events/forms.py
from django import forms
from django.utils import timezone

from .models import Event, Comment


# Forms
class AddEventForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"placeholder": "YYYY-MM-DD / hh-mm-ss"}),
    )

    class Meta:
        model = Event
        exclude = ("user", "slug", "users_attending")

    def clean_date(self):
        date_of_event = self.cleaned_data["date"]
        if date_of_event < timezone.now():
            raise forms.ValidationError(
                "The date you set is in the past. Only future events can be posted."
            )
        return date_of_event


class EditEventForm(forms.ModelForm):
    date_of_event = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"placeholder": "YYYY-MM-DD / hh-mm-ss"}),
    )

    class Meta:
        model = Event
        exclude = ("user", "slug", "users_attending")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("username", "comment")

events/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.text import slugify
from django.utils.decorators import method_decorator
from django.views import View

from taggit.models import Tag

from .forms import AddEventForm, CommentForm, EditEventForm
from .models import Category, Event


# Create your views here.
def get_event(slug: str) -> Event:
    queryset = get_object_or_404(Event, slug=slug, make_private=False)
    return queryset


def get_private_event(slug: str) -> Event:
    queryset = get_object_or_404(Event, slug=slug, make_private=True)
    return queryset


class IndexView(View):

    template_name: str = "index.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, self.template_name)


# Category views.
class CategoryListView(View):

    template_name: str = "categories.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        categories = Category.objects.all()
        events = []
        for category in categories:
            events.append((category, Event.public.filter(category=category)))
        context = {
            "categories": categories,
            "events": events,
        }
        return render(request, self.template_name, context)


class CategoryDetailView(View):

    template_name: str = "category.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        category = Category.objects.get(slug=slug)
        if request.user.is_authenticated:
            queryset = (
                category.events(manager="public").all() |
                category.events(manager="private").filter(user=request.user)
            )
        else:
            queryset = category.events(manager="public").all()
        context = {"queryset": queryset, "category": category}
        return render(request, self.template_name, context)


# Event Views
class EventsListView(View):

    template_name: str = "homepage.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        events = Event.public.all()
        context = {"events": events}
        return render(request, self.template_name, context)


class EventDetailView(View):

    form_class = CommentForm
    template_name: str = "event_detail.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_event(slug)
        tags = event.tags.all()
        related_events = (
            Event.public.filter(tags__id__in=tags).exclude(id=event.id)
        ).distinct()
        form = self.form_class()
        comments = event.comments.all()
        for comment in comments:
            print(comment.replies.all())
        context = {
            "event": event,
            "tags": tags,
            "related_events": related_events,
            "comments": comments,
            "form": form,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_event(slug)
        event_action = request.POST.get(str(event.id))
        if event_action == "Add to attend-list":
            event.users_attending.add(request.user)
            return HttpResponse("This evnt has been added to your evnt list.")
        if event_action == "Remove from attend-list":
            event.users_attending.remove(request.user)
            return HttpResponse("This evnt has been removed from your attend-list")

        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.event = get_event(slug)
            comment.username = request.user
            comment.save()
            return redirect(event.get_absolute_url())


class EventTagView(View):

    template_name: str = "event_tag.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        events = Event.objects.filter(tags__slug__contains=slug)
        tag = get_object_or_404(Tag, slug=slug)
        context = {"events": events, "tag": tag}
        return render(request, self.template_name, context)


class ManageEventsView(LoginRequiredMixin, View):

    template_name: str = "manage_events.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, self.template_name)


class PrivateEventsView(LoginRequiredMixin, View):

    template_name: str = "private_events.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        my_events = Event.private.filter(user=request.user)
        context = {"my_events": my_events}
        return render(request, self.template_name, context)


class PrivateEventDetailView(LoginRequiredMixin, View):

    template_name: str = "private_event_detail.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_private_event(slug)
        if request.user == event.user:
            event = Event.private.get(user=request.user, name=event)
            tags = event.tags.all()
        else:
            return HttpResponseForbidden()
        context = {"event": event, "tags": tags}
        return render(request, self.template_name, context)


class AddEventView(LoginRequiredMixin, View):

    form_class = AddEventForm
    template_name: str = "add_event.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.slug = slugify(event.name)
            event.save()
            form.save_m2m()
            messages.success(request, "Evnt posted successfully.")
            return redirect(event)
        messages.error(request, "Your evnt was not posted. Try again.")
        context = {"form": form}
        return render(request, self.template_name, context)


class EditEventView(LoginRequiredMixin, View):

    form_class = EditEventForm
    template_name: str = "edit_event.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_object_or_404(Event, slug=slug)
        if request.user == event.user:
            form = self.form_class(instance=event)
        else:
            return HttpResponseForbidden()
        context = {"form": form, "event": event}
        return render(request, self.template_name, context)

    def post(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_object_or_404(Event, slug=slug)
        if request.user == event.user:
            form = self.form_class(
                instance=event, data=request.POST, files=request.FILES
            )
            if form.is_valid():
                edit = form.save(commit=False)
                edit.slug = slugify(edit.name)
                edit.save()
                form.save_m2m()
                messages.success(request, "Changes saved!")
                return redirect(event.get_absolute_url())
            messages.error(request, "Error while updating evnt.")
        else:
            return HttpResponseForbidden()
        context = {"form": form, "event": event}
        return render(request, self.template_name, context)


class DeleteEventView(LoginRequiredMixin, View):

    template_name: str = "delete_event.html"

    def get(self, request: HttpRequest, slug: str) -> HttpResponse:
        event = get_object_or_404(Event, slug=slug)
        if request.user.is_superuser or request.user == event.user:
            context = {"event": event}
            return render(request, self.template_name, context)
        return HttpResponseForbidden()

    def post(self, request: HttpRequest, slug) -> HttpResponse:
        event = get_object_or_404(Event, slug=slug)
        if request.user.is_superuser or request.user == event.user:
            event.delete()
            return redirect("events:home")
        return HttpResponseForbidden()


class SearchEventView(View):

    template_name: str = "search_events.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        query = request.GET.get("search")
        search_results = None
        if not query:
            pass
        else:
            if request.user.is_authenticated:
                search_results = (
                    Event.private.filter(name__icontains=query, user=request.user)
                    | Event.public.filter(name__icontains=query)
                ).distinct()
            else:
                search_results = Event.public.filter(name__icontains=query)
        context = {"search_results": search_results, "query": query}
        return render(request, self.template_name, context)


class Attendlist(LoginRequiredMixin, View):

    template_name: str = "attend_list.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        all_events = Event.public.all()[:7]
        attend_list = Event.public.filter(users_attending=request.user)
        users_attending = []
        for event in attend_list:
            users_attending += event.users_attending.exclude(id=request.user.id)
        users_count = len(users_attending)
        max_attndts_events = {}
        for events in all_events:
            max_attndts_events[events] = events.users_attending.count()
        max_attndts_events = {
            key: value
            for key, value in sorted(
                max_attndts_events.items(), key=lambda item: item[1], reverse=True
            )
        }
        context = {
            "events": attend_list,
            "users": users_count,

events/templates/add_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}
    {{form|crispy}}
    <p> <input type="submit" value="Add" > </p>
</form>
{% endblock content %}

events/templates/add_event.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Add an evnt </h2> 
{% endblock title %}


{% block content %}
{% if form.errors %}
    <ol>
        <li> <strong> {{ form.errors }} </strong> </li>
    </ol>
{% endif %}

{% if messages %}
    <div class="alert alert-danger w-75 m-5" role="alert">
        {% for message in messages %}
            <span> {{ message }} </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        {% endfor %}
    </div>
{% endif %}

<div class="form-control p-5">
    <form enctype="multipart/form-data" method="post" action="" class="form-group">
        {% csrf_token %} 
        {{ form.media }}
        {% bootstrap_form form %} <hr>
        <button class="btn btn-outline-success submit"> Add Event </button>
    </form>
</div>
{%  endblock %}


{% block footer %} {% endblock %}

events/templates/attend_list.html
{% extends 'base.html' %}


{% block title %}
<h2> My Attend-list </h2>
{% endblock %}


{% block content %}
<div class="container-flum">
    <div class="attend-list">
        <div>
            <h4> Evnts in your "attend-list" are evnts you want to attend. </h4>
        </div>

        {% if events %}
            <div>
                {% for event in events %}
                    <div class="p-2 my-5 border">
                        <div id="posted-by" class="mb-5 card-header border">
                            {% if event.user.image %}
                                <img src="{{ event.user.image.url }}" alt="My Avi">
                            {% else %}
                                <img src="/static/images/anon.png" alt="anon">
                            {% endif %}
                            <span> <a href="{{ event.user.get_absolute_url }}"> {{ event.user }} </a> </span> 
                            <span> &sdot; {{ event.date_posted|timesince }} ago </span>
                        </div>

                        {% if event.past_event %}
                            <p class="badge bg-secondary" id="badge"> Past evnt </p>
                        {% endif %}
                
                        <div class="px-5">
                            {% if event.image %}
                                <div class="text-center"><img src="{{ event.image.url }}" alt=""></div>
                            {% endif %} 
                            <a href="{{ event.get_absolute_url }}"> {{ event }} </a>
                            <p> {{ event.description|truncatewords:25|safe }} </p> 
                        </div>
                
                        {% if event.users_attending.count %}
                            <div class="card-footer border">
                                <span> {{ users }} other{{ users|pluralize }} {{ users|pluralize:"is, are"}} attending this evnt.</span>
                            </div> 
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <div class="other-events p-3">
        <h5> Evnts with highest attendees </h5>
        {% for event, event_count in max_attndts.items %}
            <div class="card-body">
                <span id="posted-by"> <a href="{{ event.user.get_absolute_url }}"> {{ event.user }} </a> &sdot;{{ event.date_posted|timesince }} ago</span> <br>
                <a href="{{ event.get_absolute_url }}"> {{ event }} </a> <br> Users attending: {{ event_count }}
                <hr>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}


{% block footer %}{% endblock %}

events/templates/edit_event.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
<h2> Edit evnt </h2> 
{% endblock title %}


{% block content %}
{% if form.errors %}
    <ol>
        <li><strong>{{ form.errors }} </strong> </li>
    </ol>
{% endif %}

{% if messages %}
    <div class="alert alert-danger w-75 m-5" role="alert">
        {% for message in messages %}
            <span> {{ message }} </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        {% endfor %}
    </div>
{% endif %}

<div class="form-control p-5">
    <form enctype="multipart/form-data" method="post" action="" class="form-group">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %} <hr>
        <button class="btn btn-primary submit"> Save changes </button>
    </form>
</div>

{% endblock %}

events/templates/event_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load comments %}


{% block title %}
<h2> Evnt: {{ event.name }} </h2>
{% endblock title %}


{% block content %}
<div class="event-detail">
    {% if messages %}
        <div class="alert alert-success w-75 m-5" role="alert">
            {% for message in messages %}
                <span> {{ message }} </span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            {% endfor %}
        </div>
    {% endif %}
   
    <div class="event">
        <div id="posted-by" class="mb-3 p-2">
            <p> Posted by: </p>
            {% if event.user.image %}
                <img src="{{ event.user.image.url }}" alt="My Avi" class="m-0">
            {% else %}
                <img src="/static/images/anon.png" alt="anon" class="m-0">
            {% endif %}
            <span> <a href="{{ event.user.get_absolute_url }}"> {{ event.user }} </a> </span> 
            <span> &sdot;&nbsp; {{ event.date_posted|timesince }} ago </span> 
            <div class="badge bg-primary py-1" id="badge">
                <p> {{ event.users_attending.count }} user{{ event.users_attending.count|pluralize }} {{ event.users_attending.count|pluralize:"is, are"}} attending this evnt. </p>
            </div>
        </div>


        <div>
            <p> Category: <a href="{{ event.category.get_absolute_url }}"> {{ event.category }} </a> </p>
            {% if tags %}
                <p> Tags:
                    {% for tag in tags %}
                        <a href="{% url 'events:event-tag' tag.slug %}"> {{ tag }}</a>
                    {% endfor %}
                </p>
            {% endif %}
        </div>

        <div class="py-2">
            {% if event.image %} <div class="image"> <img src="{{ event.image.url }}" alt=""> {% endif %} </div>
            <p> {{ event.description|safe }} </p>
            {% if event.host %} <p> Host: {{ event.host|title }} </p> {% endif %} 
            {% if event.special_guests %} <p> Special guests: {{ event.special_guests }} </p> {% endif %} 
            <p> Date of Evnt: {{ event.date_of_event }} </p>
            <p> Venue: {{ event.venue }} </p>
            <p> Ticket Price: {% if event.ticket_price %} ${{ event.ticket_price }} {% else %} Free {% endif %} </p>
        </div>

        <p class="note badge bg-success"></p>
        <div class="text-center p-5" style="margin: 0 auto;">
            <form action="" method="post" hx-post="." hx-target=".note" hx-swap="OuterHTML">
                {% csrf_token %}
                {% if request.user in event.users_attending.all %}
                    <p class="badge bg-warning">This evnt is already in your attend-list.</p><br>
                    <input type="submit" name="{{ event.id }}" class="btn btn-outline-primary" value="Remove from attend-list">
                {% else %}
                    <input type="submit" name="{{ event.id }}" class="btn btn-primary" value="Add to attend-list">
                {% endif %}
            </form>
           
            
        </div> 

        {% if user.is_superuser or user == event.user %}
            <div class="text-center">
                <p class="event-buttons">
                    <a class="btn btn-outline-primary px-2 py-1" href="{% url 'events:edit-event' event.slug %}"> Edit evnt </a>
                    <a class="btn btn-outline-danger px-2 py-1" href="{% url 'events:delete-event' event.slug %}"> Delete evnt </a>
                </p>
            </div>
        {% endif %}
    </div>

    <hr>
    <div class="cs my-5">
        {% if comments %}
            <h3> Comment Section </h3>
            {% for comment in comments %} 
                <p class="comments p-1">
                    <span style="font-weight:bold;"> {{ comment.username }}: </span> <br>
                    <span> {{ comment.comment }} <br> <i>  {{ comment.date_added|timesince }} ago </i> </span>
                    
                    <a href="." hx-get="." hx-target="outerHTML">reply</a>
                    {% for reply in comments %}
                        {{ reply.replies.all }}
                    {% endfor %}
                </p>
            {% endfor %} 
            <hr>
        {% endif %}
    </div>
    
    <h3> Add Comment</h3>
    <form action="" class="cs" method="post">
       {% csrf_token %}
        <p> <label for="username">Username: </label> <br>
            <input id="username" name="username" required type="text"> </p>
        
        <p> <label for="comment">Comment: </label> <br>
            <textarea id="comment" name="comment" required> </textarea> </p>
        <button class="btn btn-outline-success py-1 px-2 mp-3" type="submit"> Post comment </button>
    </form>


{% if related_events %}
    <hr>
    <div class="related mt-5">
       <h3> Related Events </h3>
        <div class="events my-5">
            {% for events in related_events|slice:6 %}
                <ul>
                    <li class="text-center"> {% if events.image %} <img src="{{ events.image.url }}" alt=""> <br> {% endif %}
                        <a href="{{  events.get_absolute_url  }}"> {{ events }}</a> <br> </li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endif %}
{% endblock %}


{% block footer %}
{% endblock %}















<hr>
<div class="cs my-5">
    {% if comment_set %}
        <h3> Comment Section </h3>
        {% for comments in comment_set %} 
            <p class="comments p-1">
                <span style="font-weight:bold;"> {{ comments.username }}: </span> <br>
                <span> {{ comments.comment }} <br> <i>  {{ comments.date_added|timesince }} ago </i> </span>
            </p>
        {% endfor %} 
        <hr>
    {% endif %}
</div>

<h3> Add Comment</h3>
<form action="" class="cs" method="post">
   {% csrf_token %}
    <p> <label for="username">Username: </label> <br>
        <input id="username" name="username" required type="text"> </p>
    
    <p> <label for="comment">Comment: </label> <br>
        <textarea id="comment" name="comment" required> </textarea> </p>
    <button class="btn btn-outline-success py-1 px-2 mp-3" type="submit"> Post comment </button>
</form>

{% if related_events %}
    <hr>
    <div class="related mt-5">
       <h3> Related Events </h3>
        <div class="events my-5">
            {% for events in related_events %}
                <ul>
                    <li class="text-center"> {% if events.image %} <img src="{{ events.image.url }}" alt=""> <br> {% endif %}
                        <a href="{{  events.get_absolute_url  }}"> {{ events }}</a> <br> </li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endif %}
</div>

events/templates/event_list.html
{% extends 'base.html' %}


{% block content %}
{% for events in events %}
{{ events }}
{% endfor %}
{% endblock %}


{% block footer %} {% endblock %}

events/templates/manage_events.html
{% extends 'base.html' %}


{% block title %}
<h2> Manage Your Evnts</h2>
{% endblock %}


{% block content %}
<div class="container-1">
    <a href="{% url 'events:private-events' %}">Private Evnts</a> <br>
    <a href="{% url 'events:attend-list' %}">My Attend-list</a>
</div>
{% endblock content %}


{% block footer %}{% endblock footer %}

events/templates/private_event_detail.html
{% extends 'base.html' %}


{% block title %}
<h2> Evnt: {{ event.name }} </h2> 
{% endblock title %}


{% block content %}
<div class="event-detail">
    <div id="alert">
        {% if messages %}
            <div class="alert alert-success w-75 m-5" role="alert">
                {% for message in messages %}
                    <span> {{ message }} </span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <span class="badge bg-danger">Private evnt</span>

    <div id="event">
        <div id="posted-by" class="my-3">
            <span> You posted <br> &sdot; {{ event.date_posted|timesince }} ago </span>
        </div>

        <div>
            <p> Category: <a href="{{ event.category.get_absolute_url }}"> {{ event.category }} </a> </p>
            {% if tags %}
                <p> Tags:
                    {% for tag in tags %}
                        <a href="{% url 'events:event-tag' tag.slug %}"> {{ tag }}</a>
                    {% endfor %}
                </p>
            {% endif %}
        </div>
        
        <div class="py-2">
            {% if event.image %} <div class="image"> <img src="{{ event.image.url }}" alt=""> {% endif %} </div>
            <p> {{ event.description|safe }} </p>
            {% if event.host %} <p> Host: {{ event.host|title }} </p> {% endif %} 
            {% if event.special_guests %} <p> Special guests: {{ event.special_guests }} </p> {% endif %} 
            <p> Date of Evnt: {{ event.date_of_event }} </p>
            <p> Venue: {{ event.venue }} </p>
            <p> Ticket Price: {% if event.ticket_price %} ${{ event.ticket_price }} {% else %} Free {% endif %} </p>
        </div>

        {% comment %} <form id="hmm" action="" method="post" class="mt-5" hx-trigger="click" hx-post="." hx-target="#hmm">
            {% csrf_token %}
            <input type="submit" name="{{ event.id }}" class="btn btn-outline-primary" value="Add">
        </form> {% endcomment %}

        {% if user.is_superuser or user == event.user %}
            <div class="text-center">
                <p class="event-buttons">
                    <a class="btn btn-outline-primary px-2 py-1" href="{% url 'events:edit-event' event.slug %}"> Edit evnt </a>
                    <a class="btn btn-outline-danger px-2 py-1" href="{% url 'events:delete-event' event.slug %}"> Delete evnt</a>
                </p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block footer %}{% endblock footer %}